class EmailError(Exception):
    pass

class ValueError(Exception):
    pass